version: '3' 

services:
  server: 
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf